# Generated by Django 3.2.4 on 2021-07-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210704_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
