# Generated by Django 3.2.4 on 2021-07-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(blank=True, default='project_cover_default.png', null=True, upload_to='project_cover_images'),
        ),
    ]
